[config]
default_to_workspace = false

[env]
HOST = "0.0.0.0"
PORT = 8080
DATABASE_USERNAME = "app"
DATABASE_PASSWORD = "passwd"
DATABASE_NAME = "app"
DATABASE_PORT_OUTER = 5432
DATABASE_PORT_INNER = 5432

# Docker Composeのネットワーク内でのDB等への接続情報
[tasks.set-env-docker.env]
DATABASE_HOST = "postgres"
DATABASE_PORT = "${DATABASE_PORT_INNER}"
DATABASE_URL = "postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"

# Docker Compose外からDB等にアクセスする際の接続情報
[tasks.set-env-local.env]
DATABASE_HOST = "localhost"
DATABASE_PORT = "${DATABASE_PORT_OUTER}"
DATABASE_URL = "postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"

[tasks.before-build]
run_task = { name = ["compose-up-db", "migrate"] }

[tasks.build]
extend = "set-env-local"
dependencies = ["before-build"]
command = "cargo"
args = ["build", "${@}"]

[tasks.test]
extend = "set-env-local"
dependencies = ["before-build"]
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = [
    "nextest", "--help",
] }
command = "cargo"
args = [
    "nextest", "run", "--workspace",
    "--status-level", "all", "--test-threads=1",
]

[tasks.test-ci]
dependencies = ["before-build"]
run_task = "test"

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all", "--all-targets", "${@}"]

[tasks.clippy-ci]
command = "cargo"
args = ["clippy", "--", "--no-deps", "-Dwarnings"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "${@}"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.pre-commit]
description = "Run fmt and clippy before commit"
dependencies = ["fmt-check", "clippy"]

[tasks.check]
description = "Format and lint"
dependencies = ["fmt", "clippy"]

[tasks.features-prune]
command = "cargo"
args = ["features", "prune"]


[tasks.sqlx]
extend = "set-env-local"
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.8.6" }
command = "sqlx"
args = ["${@}", "--source", "adapter/migrations"]

[tasks.compose]
extend = "set-env-docker"
command = "docker"
args = ["compose", "${@}"]


[tasks.psql]
extend = "set-env-local"
command = "docker"
args = [
    "run", "-it", "--rm",
    "--network", "host",
    "-v", "${WORK_DIR}:/work",
    "postgres:18.1", "psql", "${DATABASE_URL}", "${@}"
]
windows = { args = [
    "run", "-it", "--rm",
    "--network", "host",
    "-v", "${$PWD}/work",
    "postgres:18.1", "psql", "${DATABASE_URL}", "${@}"
] }

[tasks.sqlx-create]
extend = "set-env-local"
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.8.6" }
command = "sqlx"
args = ["database", "create"]

[tasks.compose-up-db]
extend = "set-env-docker"
command = "docker"
args = ["compose", "up", "-d", "postgres"]

[tasks.migrate]
extend = "set-env-local"
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help", version = "0.8.6" }
script_runner = "@duckscript"
script = '''
exit_code = set 1
while ${exit_code}
    result = exec sqlx migrate run --source adapter/migrations
    exit_code = set ${result.code}
    if ${exit_code}
        echo "Migration failed, retrying in 1 second..."
        sleep 1000
    end
end
'''

