CREATE TABLE sample
(
    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    age   SMALLINT     NOT NULL CHECK (age >= 0 AND age <= 100)
);
