[package]
name = "adapter"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
shared.workspace = true
kernel.workspace = true
async-trait.workspace = true
derive-new.workspace = true
shaku.workspace = true
sqlx.workspace = true

[dev-dependencies]
